In [1]:
import numpy as np

In [2]:
np.random.seed(42)
vector_nums = np.random.normal(loc = 2, scale = 1, size = 10)

print(vector_nums)

[2.49671415 1.8617357  2.64768854 3.52302986 1.76584663 1.76586304
 3.57921282 2.76743473 1.53052561 2.54256004]


In [5]:
np.sin(vector_nums)

array([ 0.60110134,  0.95797484,  0.47406702, -0.37225477,  0.98103792,
        0.98103474, -0.4237851 ,  0.36548884,  0.99918924,  0.56384379])

In [6]:
np.exp(vector_nums)

array([12.14252984,  6.43489613, 14.12135991, 33.88694566,  5.84652008,
        5.84661606, 35.84531286, 15.91774826,  4.62060484, 12.71217307])

In [7]:
np.log10(vector_nums)

array([0.39736882, 0.26991803, 0.4228669 , 0.54691632, 0.24695298,
       0.24695702, 0.55378752, 0.44207739, 0.1848406 , 0.40527122])

In [8]:
np.mean(vector_nums)

np.float64(2.4480611116987565)

In [9]:
np.var(vector_nums)

np.float64(0.4704669452131567)

In [10]:
np.quantile(vector_nums, [0.25, 0.5, 0.75])

array([1.78983121, 2.5196371 , 2.73749818])